# Generated by Django 5.2 on 2025-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('exchange', 'Exchange')], default='sale', max_length=10),
        ),
    ]
