# Generated by Django 5.2 on 2025-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exchange_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
