# Generated by Django 5.2 on 2025-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_exchange_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exchange_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='exchange_for',
        ),
        migrations.AddField(
            model_name='product',
            name='exchange_for',
            field=models.ManyToManyField(blank=True, related_name='exchange_products', to='products.category'),
        ),
    ]
