# Generated by Django 5.2 on 2025-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_videos/thumbnails/'),
        ),
    ]
