# Generated by Django 5.2 on 2025-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accept_full_barter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='accept_full_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='accept_half_barter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='accept_half_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cannot_give_extra_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='will_give_extra_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='will_receive_extra_cash',
            field=models.BooleanField(default=False),
        ),
    ]
