# Generated by Django 5.2 on 2025-07-03 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_accept_full_barter_product_accept_full_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCategoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_notes', to='products.product')),
            ],
        ),
    ]
