# Generated by Django 5.2 on 2025-07-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_district_product_province_alter_product_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecategorynote',
            name='note',
        ),
        migrations.CreateModel(
            name='ExchangeItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.exchangecategorynote')),
            ],
        ),
    ]
