# Generated by Django 5.2 on 2025-07-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_exchangecategorynote_note_exchangeitemnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeitemnote',
            name='category_note',
        ),
        migrations.CreateModel(
            name='ExchangeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_notes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.exchangenote')),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeCategoryNote',
        ),
        migrations.DeleteModel(
            name='ExchangeItemNote',
        ),
    ]
