# Generated by Django 5.2 on 2025-07-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_exchangeitemnote_category_note_exchangenote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_rows', to='products.product')),
            ],
        ),
    ]
