# Generated by Django 5.2 on 2025-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_description_en_product_description_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailrow',
            name='label_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetailrow',
            name='label_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetailrow',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productdetailrow',
            name='value_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
